pod "MJRefresh","~> 2.2.1"
pod "MBProgressHUD","~> 0.9.1"
pod 'JPush-iOS-SDK', '~> 1.8.3.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'PinYin4Objc', '~> 1.1.1'
pod 'MWPhotoBrowser', '~> 2.1.1'
pod 'FMDB', '~> 2.5'